### ISSUE TITLE
Crash on Windows 7

### ISSUE THREAD

**Issue by ofirdev** [db9052/pdf2svg#3]
When trying to convert the following PDF on Windows 7,  pdf2svg crashes and I see a message:
pdf2svg.exe has stopped working.
https://drive.google.com/file/d/0B0odzw1WMqkGbWxwYXdwM1RIWEk/view

Some PDFs work fine.

Tested on a clean Windows 7 64 bit with only Office 2013 installed.
I'm using the following pdf2svg version:
http://www.cityinthesky.co.uk/wp-content/uploads/2014/06/pdf2svg-w32bin-0.2.2.zip

Thanks

**Comment by jhabjan** [comment]
A same here. Any solution?

**Comment by Finetuned** [comment]
bump

**Comment by RonanKER** [comment]
The following repository may interest you : https://github.com/jalios/pdf2svg-windows

We store there windows binaries for 32 and 64bit with updated version of cairo.

It's quite better, but there is still some crash with some pdf files...

**Comment by db9052** [comment]
RonanKER - thanks, I'll add a link to your binaries from the README if that's OK.

All - PDF2SVG is incredibly simple in itself, as such the crashes will come from the underlying libraries (Cairo and Poppler). All that can be done is to update the libraries used and recompile. Please see RonanKER's comment.

**Comment by RonanKER** [comment]
That's OK David :-)

We still experience some crash with some files, we don't have immediate time to investigate, but maybe if anybody perform a better recompile (or if we find it), we'll merge the best pull request ;-)

I think also we should try to recompile from a windows plateform (we did from a fedora), and perhaps build different binaries for each windows version. (we don't experience the same crashes on "Seven" and on "Server 2012")
