### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hurzl** [db9052/pdf2svg#4]
One could trigger a new release that includes the latest bugfixes?

**Comment by db9052** [comment]
There are no new bugfixes in PDF2SVG; any bugfixes will come from changes in the underlying libraries (Cairo and Poppler) which should be automatically brought in when your Linux distro rebuilds the software. (Hopefully!)

**Comment by hurzl** [comment]
release 0.2.2  says "6 commits to master since this release"

**Comment by db9052** [comment]
Yes, but these are mostly changes to the docs and don't affect the working of the software at all. (I'm pretty sure that the one bug fix in those 6 commits was actually in the release anyway.)

**Comment by hurzl** [comment]
no, https://github.com/db9052/pdf2svg/commit/ae2e6fede4ec0b29754e7f8692c6f6d59aeaf8b9  is not

**Comment by db9052** [comment]
In that case, a new release has been issued...

**Comment by hurzl** [comment]
thank you so much :)
