### ISSUE TITLE
gtk+ dependency

### ISSUE THREAD

**Issue by tschoonj** [db9052/pdf2svg#7]
Hi,

I was checking the Homebrew formula for pdf2svg and I realized that there is absolutely no need to enforce a gtk+ dependency since it is nowhere used by pdf2svg.c. You can safely remove all references to gtk+ from configure.ac and Makefile.am

Oh and autoreconf complains because it cannot find README...

**Comment by db9052** [comment]
Thanks, I've made those changes.
